#This file starts up a server at http://127.0.0.1:5000/
#All the files in the "static" and "templates" folder are built in angular and generated by
#runnign ng build --base-href

#from flask_cors import CORS
import requests
from flask import Flask, render_template, make_response,jsonify,request
#from flask_cors import CORS
#from 'c:\users\louis\appdata\local\programs\python\python38-32\lib\site-packages\flask_cors' import CORS

#from flask.ext.cors import CORS 

app = Flask(__name__)
#CORS(app)

#app = Flask(__name__, static_folder="static", static_url_path='')
a={'first':3,'second':4}




def _build_cors_prelight_response():
    response = make_response()
    response.headers.add('Access-Control-Allow-Origin', "*")
    response.headers.add('Access-Control-Allow-Headers', "*")
    response.headers.add('Access-Control-Allow-Methods', "*")
    return response

def _corsify_actual_response(response):
    response.headers.add("Access-Control-Allow-Origin", "*")
    print(request.data)
    return response



@app.route('/')
def hello_world():
    return "hello world"




#This is a get Endpoint, since it is accessed through a URL. Because i send hidden payloads in the body when posting. 
@app.route('/testpage')
def somethingelse():
    if request.method == "OPTIONS":
        return _build_cors_prelight_response()
    if request.method == "GET":
        return _corsify_actual_response(jsonify(a))

@app.route('/testpagepost', methods = ['POST'])
def somethingelse2():
    if request.method == "OPTIONS":
        return _build_cors_prelight_response()
    if request.method == "POST":
        return _corsify_actual_response(jsonify(a))
    




app.run()

