#This file starts up a server at http://127.0.0.1:5000/
#All the files in the "static" and "templates" folder are built in angular and generated by
#runnign ng build --base-href


from flask import Flask, render_template
app = Flask(__name__, static_folder="static", static_url_path='')


@app.route('/')
def hello_world():
    return render_template('index.html')
    
app.run()